version: '3.4'

services:
  events.connector:
    image: ${DOCKER_REGISTRY-}events
    build:
      context: .
      dockerfile: events.connector/Dockerfile

  events.connector.api:
    image: ${DOCKER_REGISTRY-}eventsconnector
    build:
      context: .
      dockerfile: events.connector.api/Dockerfile

